# Generated by Django 6.0.1 on 2026-01-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('career', 'Career'), ('social', 'Social'), ('sports', 'Sports')], default='social', max_length=20)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('interested_count', models.IntegerField(default=0)),
            ],
        ),
    ]
