# Generated by Django 6.0.1 on 2026-01-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('career', 'Career'), ('social', 'Social'), ('sports', 'Sports')], default='social', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('members', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
